services:
  - type: web
    name: robododark-gateway
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    plan: free
    autoDeploy: true
    envVars:
      - key: LOCAL_API_URL
        value: http://localhost:8000/transcribe
